=== activey/DOA/doa-api/src/main/resources/schema/deploy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://doaplatform.org/deploy"
	elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://doaplatform.org/deploy">

	<xsd:complexType name="DeployType">
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="container" type="ContainerType">
			</xsd:element>
			<xsd:element name="agent" type="AgentType"></xsd:element>
			<xsd:element name="load" type="LoadType"></xsd:element>
			<xsd:element name="documentAligner" type="AlignerType">
			</xsd:element>
			<xsd:element name="definition"
				type="DocumentDefinitionType">
			</xsd:element>
			<xsd:element name="document" type="DocumentType">
			</xsd:element>
			<xsd:element name="lookup" type="LookupType"></xsd:element>
			<xsd:element name="renderer" type="RendererType">
			</xsd:element>
			<xsd:element name="service" type="ServiceDefinitionType">
			</xsd:element>
			<xsd:element name="resource" type="StaticResourceType">
			</xsd:element>
			<xsd:element name="channel" type="ChannelType">
			</xsd:element>
			<xsd:element name="reference" type="ReferenceType"></xsd:element>
			<xsd:element name="doa" type="DOAType"></xsd:element>
            <xsd:element name="deploy-processor" type="DeployProcessorType"></xsd:element>
		</xsd:choice>
		<xsd:attribute name="defaultContainer" type="xsd:string"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="ContainerType">
		<xsd:complexContent>
			<xsd:extension base="EntityType">
				<xsd:choice minOccurs="0" maxOccurs="unbounded">
					<xsd:element name="container"
						type="ContainerType">
					</xsd:element>
					<xsd:element name="agent" type="AgentType">
					</xsd:element>
					<xsd:element name="load" type="LoadType"></xsd:element>
					<xsd:element name="documentAligner"
						type="AlignerType">
					</xsd:element>
					<xsd:element name="definition"
						type="DocumentDefinitionType">
					</xsd:element>
					<xsd:element name="document" type="DocumentType">
					</xsd:element>
					<xsd:element name="lookup" type="LookupType">
					</xsd:element>
					<xsd:element name="renderer" type="RendererType">
					</xsd:element>
					<xsd:element name="service"
						type="ServiceDefinitionType">
					</xsd:element>
					<xsd:element name="resource"
						type="StaticResourceType">
					</xsd:element>
					<xsd:element name="channel" type="ChannelType">
					</xsd:element>
					<xsd:element name="reference"
						type="ReferenceType">
					</xsd:element>
					<xsd:element name="doa" type="DOAType"></xsd:element>
				</xsd:choice>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="DocumentType">
		<xsd:complexContent>
			<xsd:extension base="EntityType">
				<xsd:sequence>
					<xsd:element name="fieldValue" type="FieldValueType"
						maxOccurs="unbounded" minOccurs="0">
					</xsd:element>
				</xsd:sequence>
				<xsd:attribute name="definition" type="xsd:string"
					use="required"></xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="AgentType">
		<xsd:complexContent>
			<xsd:extension base="EntityType">

			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="AttributeType" mixed="true">
		<xsd:attribute name="name" type="xsd:string"></xsd:attribute>
		<xsd:attribute name="value" type="xsd:string"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="LookupType">
		<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
		<xsd:attribute name="location" type="xsd:string" use="required">
		</xsd:attribute>
		<xsd:attribute name="doa" type="xsd:string"></xsd:attribute>
		<xsd:attribute name="var" type="xsd:string"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="RendererType">
		<xsd:complexContent>
			<xsd:extension base="EntityType">
				<xsd:attribute name="logicClass" type="xsd:string"
					use="required">
				</xsd:attribute>

				<xsd:attribute name="mimetype" type="xsd:string" use="required">
				</xsd:attribute>

				<xsd:attribute name="autostart" type="xsd:boolean"></xsd:attribute>

			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="ServiceDefinitionType">
		<xsd:complexContent>
			<xsd:extension base="EntityType">
				<xsd:sequence>
					<xsd:element name="possibleOutput" type="PossibleOutputType"
						maxOccurs="unbounded" minOccurs="0"></xsd:element>
				</xsd:sequence>
				<xsd:attribute name="logicClass" type="xsd:string">
				</xsd:attribute>
				<xsd:attribute name="inputDefinition" type="xsd:string">
				</xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="PossibleOutputType">
		<xsd:attribute name="doa" type="xsd:string"></xsd:attribute>
		<xsd:attribute name="definition" type="xsd:string"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="StaticResourceType">
		<xsd:complexContent>
			<xsd:extension base="EntityType">
				<xsd:attribute name="file" type="xsd:string"></xsd:attribute>
				<xsd:attribute name="url" type="xsd:string"></xsd:attribute>
				<xsd:attribute name="mimetype" type="xsd:string"
					use="required">
				</xsd:attribute>
				<xsd:attribute name="path" type="xsd:string"></xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="AlignerType">
		<xsd:complexContent>
			<xsd:extension base="EntityType">
				<xsd:attribute name="logicClass" type="xsd:string"
					use="required"></xsd:attribute>
				<xsd:attribute name="fromDefinition" type="xsd:string"></xsd:attribute>
				<xsd:attribute name="toDefinition" type="xsd:string"></xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="DocumentDefinitionType">
		<xsd:complexContent>
			<xsd:extension base="EntityType">

				<xsd:choice minOccurs="0" maxOccurs="unbounded">
					<xsd:element name="stringField" type="StringFieldType">
					</xsd:element>
					<xsd:element name="booleanField" type="BooleanFieldType">
					</xsd:element>
					<xsd:element name="doubleField" type="DoubleFieldType"></xsd:element>
					<xsd:element name="integerField" type="IntegerFieldType">
					</xsd:element>
					<xsd:element name="longField" type="LongFieldType">
					</xsd:element>
					<xsd:element name="bigdecimalField" type="BigDecimalFieldType">
					</xsd:element>
					<xsd:element name="dateField" type="DateFieldType">
					</xsd:element>
					<xsd:element name="passwordField" type="PasswordFieldType">
					</xsd:element>
					<xsd:element name="referenceField" type="ReferenceFieldType">
					</xsd:element>
					<xsd:element name="listField" type="ListFieldType">
					</xsd:element>
					<xsd:element name="fieldType" type="FieldTypeType"></xsd:element>
				</xsd:choice>

			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:simpleType name="DocumentFieldDataType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="string"></xsd:enumeration>
			<xsd:enumeration value="bool"></xsd:enumeration>
			<xsd:enumeration value="doubleprec"></xsd:enumeration>
			<xsd:enumeration value="integer"></xsd:enumeration>
			<xsd:enumeration value="longinteger"></xsd:enumeration>
			<xsd:enumeration value="bigdecimal"></xsd:enumeration>
			<xsd:enumeration value="date"></xsd:enumeration>
			<xsd:enumeration value="password"></xsd:enumeration>
			<xsd:enumeration value="reference"></xsd:enumeration>
			<xsd:enumeration value="list"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="FieldTypeType">
		<xsd:sequence>
			<xsd:element name="fieldValidator" type="FieldValidatorType"
				maxOccurs="1" minOccurs="0"></xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
		<xsd:attribute name="dataType" use="required"
			type="DocumentFieldDataType">
		</xsd:attribute>
		<xsd:attribute name="var" type="xsd:string"></xsd:attribute>
		<xsd:attribute name="required" type="xsd:boolean"></xsd:attribute>
		<xsd:attribute name="authorizable" type="xsd:boolean"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="FieldValidatorType">
		<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
		<xsd:attribute name="validatorClass" type="xsd:string"
			use="required">
		</xsd:attribute>
		<xsd:attribute name="var" type="xsd:string"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="FieldValueType" mixed="true">
		<xsd:sequence>
			<xsd:element name="fieldValue" type="FieldValueType"
				maxOccurs="unbounded" minOccurs="0"></xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
		<xsd:attribute name="value" type="xsd:string"></xsd:attribute>
		<xsd:attribute name="var" type="xsd:string"></xsd:attribute>
		<xsd:attribute name="dataType" type="DocumentFieldDataType" />
	</xsd:complexType>

	<xsd:complexType name="EntityType" abstract="true">
		<xsd:sequence>
			<xsd:element name="attr" type="AttributeType" maxOccurs="unbounded"
				minOccurs="0">
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
		<xsd:attribute name="doa" type="xsd:string"></xsd:attribute>
		<xsd:attribute name="location" type="xsd:string"></xsd:attribute>
		<xsd:attribute name="var" type="xsd:string"></xsd:attribute>
		<xsd:attribute name="ancestor" type="xsd:string"></xsd:attribute>
	</xsd:complexType>

	<xsd:element name="deploy" type="DeployType"></xsd:element>

	<xsd:complexType name="ChannelType">
		<xsd:complexContent>
			<xsd:extension base="EventReceiverEntityType">
				<xsd:attribute name="logicClass" type="xsd:string"
					use="required">
				</xsd:attribute>
				<xsd:attribute name="autostart" type="xsd:boolean"></xsd:attribute>
				<xsd:attribute name="type" type="ChannelTypeEnum"></xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="ReferenceType">
		<xsd:complexContent>
			<xsd:extension base="EntityType">
				<xsd:attribute name="referencedEntity" type="xsd:string"></xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="LoadType">
		<xsd:attribute name="directory" type="xsd:string"></xsd:attribute>
		<xsd:attribute name="location" type="xsd:string"></xsd:attribute>
	</xsd:complexType>

    <xsd:complexType name="DeployProcessorType">
        <xsd:attribute name="processor" type="xsd:string"></xsd:attribute>
    </xsd:complexType>


	<xsd:complexType name="StringFieldType">
		<xsd:complexContent>
			<xsd:extension base="DocumentFieldType">

				<xsd:attribute name="minLength" type="xsd:int">
				</xsd:attribute>
				<xsd:attribute name="maxLength" type="xsd:int"></xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="DocumentFieldType">
		<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
		<xsd:attribute name="var" type="xsd:string"></xsd:attribute>
		<xsd:attribute name="required" type="xsd:boolean"></xsd:attribute>
		<xsd:attribute name="authorizable" type="xsd:boolean"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="BooleanFieldType">
		<xsd:complexContent>
			<xsd:extension base="DocumentFieldType"></xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="DoubleFieldType">
		<xsd:complexContent>
			<xsd:extension base="DocumentFieldType"></xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="IntegerFieldType">
		<xsd:complexContent>
			<xsd:extension base="DocumentFieldType"></xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="LongFieldType">
		<xsd:complexContent>
			<xsd:extension base="DocumentFieldType"></xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="BigDecimalFieldType">
		<xsd:complexContent>
			<xsd:extension base="DocumentFieldType"></xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="DateFieldType">
		<xsd:complexContent>
			<xsd:extension base="DocumentFieldType">
				<xsd:attribute name="format" type="xsd:string"></xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="PasswordFieldType">
		<xsd:complexContent>
			<xsd:extension base="DocumentFieldType">
				<xsd:attribute name="cipherAlgorithm" type="xsd:string"></xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="ReferenceFieldType">
		<xsd:complexContent>
			<xsd:extension base="DocumentFieldType">
				<xsd:attribute name="entityType" type="xsd:string"></xsd:attribute>
				<xsd:attribute name="definition" type="xsd:string"></xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="ListFieldType">
		<xsd:complexContent>
			<xsd:extension base="DocumentFieldType">
				<xsd:attribute name="dataType" type="DocumentFieldDataType"></xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>


	<xsd:complexType name="EventReceiverEntityType"
		abstract="true">
		<xsd:complexContent>
			<xsd:extension base="EntityType">
				<xsd:sequence>
					<xsd:element name="eventListener" type="EventListenerType"
						maxOccurs="unbounded" minOccurs="0">
					</xsd:element>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="EventListenerType">
		<xsd:complexContent>
			<xsd:extension base="EntityType">
				<xsd:attribute name="sourceEntity" type="xsd:string"></xsd:attribute>

				<xsd:attribute name="eventType" type="EventType"></xsd:attribute>

			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:simpleType name="EventType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="ENTITY_CREATED"></xsd:enumeration>
			<xsd:enumeration value="SERVICE_EXECUTED"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="DOAType">
		<xsd:complexContent>
			<xsd:extension base="EntityType">
				<xsd:attribute name="logicClass" type="xsd:string" use="required"></xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:simpleType name="ChannelTypeEnum">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="INCOMING"></xsd:enumeration>
			<xsd:enumeration value="OUTGOING"></xsd:enumeration>
			<xsd:enumeration value="TWOWAY"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== activey/DOA/channel-http-tomcat/src/main/resources/deploy.xml
<?xml version="1.0" encoding="UTF-8"?><!-- Copyright 2011 Inhibi Ltd. All 
	rights reserved. Redistribution and use in source and binary forms, with 
	or without modification, are permitted provided that the following conditions 
	are met: 1. Redistributions of source code must retain the above copyright 
	notice, this list of conditions and the following disclaimer. 2. Redistributions 
	in binary form must reproduce the above copyright notice, this list of conditions 
	and the following disclaimer in the documentation and/or other materials 
	provided with the distribution. THIS SOFTWARE IS PROVIDED BY INHIBI LTD ``AS 
	IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
	THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
	ARE DISCLAIMED. IN NO EVENT SHALL INHIBI LTD OR CONTRIBUTORS BE LIABLE FOR 
	ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
	(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
	LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND 
	ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
	(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF 
	THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. The views 
	and conclusions contained in the software and documentation are those of 
	the authors and should not be interpreted as representing official policies, 
	either expressed or implied, of Inhibi Ltd. Contributors: Inhibi Ltd - initial 
	API and implementation -->

<deploy xmlns="http://doaplatform.org/deploy" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://doaplatform.org/deploy http://doaplatform.org/schema/deploy.xsd"
	defaultContainer="/channels">

	<container name="http">
		<definition name="http_request_definition" var="http_request_definition">
			<fieldType name="asynchronous" dataType="bool" required="true" />
			<stringField name="method" required="true" />
			<stringField name="remoteAddress" authorizable="true" />
			<fieldType name="uri" dataType="string" required="true" />
			<fieldType name="rootUri" dataType="string" required="true" />
			<fieldType name="applicationUri" dataType="string" />
			<fieldType name="url" dataType="string" required="true" />
			<fieldType name="sessionId" dataType="string" authorizable="true" />
			<referenceField name="body" />
			<fieldType name="applicationContext" dataType="string"
				required="true" />
			<fieldType name="parameters" dataType="list" />
			<fieldType name="cookies" dataType="list" />
			<fieldType name="headers" dataType="list" />

			<referenceField name="applicationDocument" entityType="pl.doa.document.IDocument"
				definition="/channels/http/application_context_definition" />
		</definition>

		<definition name="http_response_definition" var="http_response_definition">
			<fieldType name="cookies" dataType="list" />
			<fieldType name="headers" dataType="list" />
			<fieldType name="httpCode" dataType="integer" />
			<fieldType name="contentType" dataType="string" />
			<fieldType name="response" dataType="reference" />
			<fieldType name="agent" dataType="reference" />
		</definition>

		<definition name="http_error_definition" var="http_error_definition">
			<fieldType name="errorCode" dataType="integer" />
		</definition>

		<definition name="http_filter_definition">
			<stringField name="filterClass" />
			<stringField name="filterMapping" />
			<listField name="initParams" />
		</definition>

		<service name="handle_session" inputDefinition="#http_request_definition"
			logicClass="pl.doa.temp.http.service.HandleSessionService">
			<possibleOutput definition="#http_response_definition" />
		</service>

		<definition name="application_context_definition" var="application_context_definition">
			<fieldType name="applicationName" dataType="string"
				required="true" />
			<fieldType name="authentication" dataType="string" />
			<fieldType name="authenticationService" dataType="reference" />
			<fieldType name="templateFinder" dataType="string" />
			<fieldType name="defaultUri" dataType="string" />
			<booleanField name="cacheEnabled" />
		</definition>

		<container name="extensions" />

		<container name="auth">
			<service name="authFacadeService"
				logicClass="pl.doa.temp.http.service.auth.AuthenticationFacadeService"
				inputDefinition="#http_request_definition">
				<possibleOutput definition="#http_response_definition" />
			</service>

			<definition name="auth_output" var="auth_output">
				<fieldType name="authenticated" dataType="reference" />
			</definition>

			<definition name="basic_auth_input" var="basic_auth_input">
				<fieldType name="login" dataType="string" />
				<fieldType name="password" dataType="password" />
				<fieldType name="applicationDocument" dataType="reference" />
			</definition>

			<documentAligner name="basic_auth_aligner"
				fromDefinition="#http_request_definition" toDefinition="#basic_auth_input"
				logicClass="pl.doa.temp.http.service.auth.aligner.BasicAuthenticationAligner" />

			<service name="BASIC" inputDefinition="#basic_auth_input"
				logicClass="pl.doa.temp.http.service.auth.BasicAuthenticationService">
				<possibleOutput definition="#auth_output" />
				<possibleOutput definition="#http_response_definition" />
			</service>
		</container>

		<!-- definicja kanalu -->
		<channel name="http_channel" autostart="true"
			logicClass="pl.doa.temp.http.HTTPChannelLogic" type="INCOMING">
			<attr name="port" value="9080" />
			<attr name="developmentMode" value="true" />
			<attr name="use.cache.2ndlevel" value="false" />
			<attr name="max-age" value="3600" />

			<eventListener name="deployListener" location="/tmp"
				sourceEntity="/applications" eventType="ENTITY_CREATED" />
		</channel>

	</container>
</deploy>

=== activey/DOA/environment/standalone/var/tmp/agent-slawek.xml
<?xml version="1.0" encoding="UTF-8"?>

<deploy xmlns="http://doaplatform.org/deploy" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://doaplatform.org/deploy http://doaplatform.org/schema/deploy.xsd"
defaultContainer="/agents">

	<container name="agent-slawek">
		<agent name="slawek" var="slawek" />
		<container name="fingerprints">
			<document name="olender-admin-login"
			definition="/applications/olender-frontpage/definitions/authentication/login_input">
				<fieldValue name="login">slavo</fieldValue>
				<fieldValue name="password">kura13</fieldValue>
			</document>
		</container>
		<container name="profile">
			<document name="user_profile"
			definition="/applications/olender-frontpage/definitions/authentication/profile_definition">
				<fieldValue name="firstName">Sławek</fieldValue>
				<fieldValue name="lastName">Śmigulec</fieldValue>
			</document>
		</container>

	</container>
	<container name="security">
		<container name="roles">
			<container name="admin">
				<reference name="slawek" referencedEntity="#slawek" />
			</container>
		</container>
	</container>

</deploy>

=== activey/DOA/environment/standalone/var/tmp/agent-agnieszka.xml
<?xml version="1.0" encoding="UTF-8"?>

<deploy xmlns="http://doaplatform.org/deploy" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://doaplatform.org/deploy http://doaplatform.org/schema/deploy.xsd"
defaultContainer="/agents">

	<container name="agent-agnieszka">
		<agent name="agnieszka" var="agnieszka" />
		<container name="fingerprints">
			<document name="olender-admin-login"
			definition="/applications/olender-frontpage/definitions/authentication/login_input">
				<fieldValue name="login">stavanger</fieldValue>
				<fieldValue name="password">escape</fieldValue>
			</document>
		</container>
		<container name="profile">
			<document name="user_profile"
			definition="/applications/olender-frontpage/definitions/authentication/profile_definition">
				<fieldValue name="firstName">Agnieszka</fieldValue>
				<fieldValue name="lastName">Borkowska</fieldValue>
			</document>
		</container>

	</container>
	<container name="security">
		<container name="roles">
			<container name="admin">
				<reference name="agnieszka" referencedEntity="#agnieszka" />
			</container>
		</container>
	</container>

</deploy>

=== activey/DOA/environment/standalone/var/tmp/agent-kamil.xml
<?xml version="1.0" encoding="UTF-8"?>

<deploy xmlns="http://doaplatform.org/deploy" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://doaplatform.org/deploy http://doaplatform.org/schema/deploy.xsd"
	defaultContainer="/agents">

	<container name="agent-kamil">
		<agent name="kamil" var="kamil" />

		<container name="fingerprints">
			<document name="olender-admin-login"
				definition="/applications/olender-frontpage/definitions/authentication/login_input">
				<fieldValue name="login">
					kamilja
				</fieldValue>
				<fieldValue name="password">
					kamil321
				</fieldValue>
			</document>
		</container>

		<container name="profile">
			<document name="user_profile"
				definition="/applications/olender-frontpage/definitions/authentication/profile_definition">
				<fieldValue name="firstName">
					Kamil
				</fieldValue>
				<fieldValue name="lastName">
					Jasiewicz
				</fieldValue>
			</document>
		</container>

	</container>

	<container name="security">
		<container name="roles">
			<container name="admin">
				<reference name="kamil" referencedEntity="#kamil" />
			</container>
		</container>
	</container>

</deploy>

=== activey/DOA/examples/wicket-test/src/main/resources/deploy.xml
<?xml version="1.0" encoding="UTF-8"?>
<deploy xmlns="http://doaplatform.org/deploy" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://doaplatform.org/deploy http://doaplatform.org/schema/deploy.xsd">

    <!-- wicket extension container -->
    <container name="wicket-test-data">
        <container name="documents">
            <definition name="first_definition">
                <stringField name="firstName" />
                <stringField name="lastName" />
                <dateField name="birthDate" />
            </definition>

            <document name="first" definition="#/wicket-test-data/documents/first_definition" />
        </container>


        <document name="app-definition" definition="/channels/http/ext/wicket/wicketApplication">
            <fieldValue name="applicationClassName">org.doa.examples.wicket.TestApplication</fieldValue>
        </document>
    </container>


    <reference name="wicket-test" referencedEntity="#/wicket-test-data/app-definition"/>
</deploy>
